//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRecord
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public System.DateTime RunTime { get; set; }
        public long Count { get; set; }
        public long Amount { get; set; }
    }
}
